name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint
      - name: Run check
        run: pnpm check
      - name: Run tsc
        run: pnpm tsc --noEmit
